// Code generated by MockGen. DO NOT EDIT.
// Source: D:\Programming\Go\url-shortner\database-server\internal\handlers\handlers.go

// Package mock_handlers is a generated GoMock package.
package mock_handlers
